### ISSUE TITLE
.htaccess like functionality?

### ISSUE THREAD

**Issue by teacoat** [greggman/hft-unity3d#11]
I am attempting to use Angular with HappyFunTimes, but the URL routing is giving me some issues.

Normally I would just rewrite it with .htaccess, but I don't think it knows what it is.

I have also been trying to get it to work just at the root of the server, but I get an infinite redirect loop and its very confusing and I'm not sure what to try here.

**Comment by greggman** [comment]
You can set the URL for the controller in the `PlayerSpawner` or `PlayerConnector`'s properties

See http://docs.happyfuntimes.net/docs/unity/happyfuntimes-options.html

On the other hand I don't think you can set it to the root. The root is used as a redirect already. It's needed to handle captive portal support.

But Angular does not have to be at the root AFAICT

https://stackoverflow.com/questions/20310871/set-angular-js-url-root-globally
