### ISSUE TITLE
Where is the 3D character example file you link to in docs?

### ISSUE THREAD

**Issue by dpentecost** [greggman/hft-unity3d#7]
at http://docs.happyfuntimes.net/docs/unity/3d-characters.html
you have a link to a page of samples that you say has the example that you then go on to explain in the rest of the page. That linked page has no sample.

Where can I find the 3D character sample?

**Comment by greggman** [comment]
Thanks for pointing that out. I had forgotten about that. 

I updated those docs. If you refresh the page it will hopefully show how to create a 3d character example

**Comment by dpentecost** [comment]
Thanks. BTW, we had 7 girls on iPod Touches playing the 2D Platform example yesterday and having fun just piling on. It's a hit! Next goal, 3D in the planetarium. Thanks again.
