### ISSUE TITLE
Installation mode on Windows

### ISSUE THREAD

**Issue by hotcakesdeluxe** [greggman/hft-unity3d#8]
Hey I've made a quick game that I'm trying to show at a big event and would like to not have to rely on bad wifi but am having a lot of trouble trying to piece together how to setup installation mode. I think I have my router correctly configured. Is it even possible on windows?

**Comment by greggman** [comment]
Installation mode should work fine on windows

What problem are you seeing specifically? What steps are you taking and what results do you see?

It's possible your router doesn't support installation mode (the netgear router I tried didn't support it)

## Things to check:

You setup installation mode on your router, open a command prompt and type `ipconfig`

<img width="430" alt="screen shot 2017-05-04 at 5 55 22 pm" src="https://cloud.githubusercontent.com/assets/234804/25696827/9964f360-30f3-11e7-8bcf-5fbc365dc2c7.png">

the IPv4 address should match the one you specified in your router configuration when assigning a static IP address for your computer

Then if you run the game, and then alt-tab back to the command prompt and type `nslookup foo.com`

<img width="352" alt="screen shot 2017-05-04 at 5 57 13 pm" src="https://cloud.githubusercontent.com/assets/234804/25696891/eea399b2-30f3-11e7-9d71-f2903eac0ccb.png">

The 1st and 2nd with the 3rd maybe being your `Default Gateway` from above numbers should match your IPv4 address from `ipconfig`

If those don't match then your router is not setup correctly or else you've maybe you manually put DNS addresses in your computer's network configuration and need to remove them.

If that all checks out then the question is are you testing Android or iPhone

It looks like Apple might have broken installation mode with the latest version of iOS. The simplest workaround at the moment is to edit `Assets/WebPlayerTemplates/HappyFunTimes/hft/captive-portal/game-login.html` and change it to this

```
<!--
/*
 * Copyright 2014, Gregg Tavares.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *     * Neither the name of Gregg Tavares. nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
-->
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">

  <meta name="HandheldFriendly" content="True">
  <meta name="MobileOptimized" content="320">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=no, minimal-ui">
  <meta name="format-detection" content="telephone=no" />
  <title>HappyFunTimes Redirect</title>
  <link rel="stylesheet" href="/hft/captive-portal/login.css">
  <style>
  </style>
</head>
<body>
  <div class="hft-center hft-fullsize">
      <h1>HappyFunTimes</h1>
      <h1>Please open your browser and go to hft.com</h1>
<!--      <a id="start" href="%(startUrl)s" target="_blank">Start</a> -->
  </div>
</body>
</html>
```

The only changes are the second `<h1>` line and commenting out the Start line

**Comment by hotcakesdeluxe** [comment]
when i nslookup foo.com it prints
Server: UnKnown
Address: 192.168.2.132 (the correct IPv4 address for the router i set)

***UnKnown can't find foo.com: no response from server

**Comment by hotcakesdeluxe** [comment]
![routersettings](https://cloud.githubusercontent.com/assets/4298208/25713044/5a142d5c-30c1-11e7-8e0a-135305847939.PNG)
this is what i setup on my router. is there something in unity i should be setting to look for the router?

**Comment by greggman** [comment]
You were running the game when you used `nslookup`?

**Comment by greggman** [comment]
Let me clarify that, you were running the game **in installation mode** when you typed `nslookup`?

**Comment by hotcakesdeluxe** [comment]
i suppose not. i'm a little unclear on what i need to do for that? i was running that npm run start -- --dns bit  and i'm not sure what to have setup, if anything, in unity.

**Comment by hotcakesdeluxe** [comment]
switched some things around, nslookup is now showing the right addresses but unity throws socketexception

**Comment by greggman** [comment]
Ugh! Sorry about that. I could have sworn I wrote docs but I can't find them anywhere 😓 

There's no node or npm to run for the unity version.

You just pick Window->HappyFuntimes->Settings and check "Installation Mode" if you're in the editor. If you build your game to an exe then you have to run it from the command line with the argument `--hft-installation-mode`

Just remember to turn off installation mode when you're not with a configured router (as in your running things like normal, going through happyfuntimes.net). Because, when installation mode is used the game will not ping happyfuntimes.net because it assumes you're not on the internet.

[I updated the docs a little](http://docs.happyfuntimes.net/docs/network.html)

**Comment by hotcakesdeluxe** [comment]
awesome i'm glad it was something easy! got it fixed just in time, here's my game i made using it running a jumbotron in Philadelphia https://www.instagram.com/p/BTsNTjuBEoe/?taken-by=space_bit
